INSERT INTO tipos_materiales (nombre) VALUES
('Libros Táctiles'),
('Pizarra Braille'),
('Dispositivos de Lectura Portátiles'),
('Teclados Braille'),
('Relojes Adaptados'),
('Calculadoras Talking'),
('Mapas en Relieve'),
('Audífonos de Alta Fidelidad'),
('Software de Reconocimiento de Voz'),
('Videos Descriptivos'),
('Etiquetas en Braille'),
('Móviles Accesibles'),
('Brazaletes Adaptativos'),
('Audífonos Bluetooth'),
('Lentes de Lectura'),
('Escáneres de Documentos'),
('Pantallas Braille'),
('Simuladores de Realidad Aumentada'),
('Cámaras Táctiles'),
('Aplicaciones de Traducción Braille'),
('Herramientas de Orientación Espacial'),
('Dispositivos de Señalización Sonora'),
('Sistemas de Navegación por Sonido'),
('Módulos de Capacitación Interactivos'),
('Sillas Adaptativas'),
('Teclados Virtuales'),
('Lentes de Aumento de Contraste'),
('Cámaras de Alta Resolución'),
('Proyectores de Táctiles Dinámicos'),
('Sensores de Proximidad Táctiles');
