INSERT INTO materiales (tipo_id, nombre, descripcion, created_at, updated_at, deleted_at) VALUES
(1, 'Libro Táctil de Geografía', 'Libro con mapas en relieve y texto en Braille para aprender geografía.', NOW(), NOW(), NULL),
(2, 'Pizarra Braille Portátil', 'Pizarra de tamaño pequeño con espacio para escribir en Braille, ideal para clases individuales.', NOW(), NOW(), NULL),
(3, 'Lector de Libros Electrónicos', 'Dispositivo portátil para leer libros electrónicos en formato accesible, como Braille o audio.', NOW(), NOW(), NULL),
(4, 'Teclado Braille para Computadora', 'Teclado adaptado con celdas Braille para su uso en computadoras y dispositivos compatibles.', NOW(), NOW(), NULL),
(5, 'Reloj Braille', 'Reloj de muñeca con indicadores en Braille para personas con ceguera.', NOW(), NOW(), NULL),
(6, 'Calculadora Talking', 'Calculadora electrónica que emite sonido para indicar cada número y operación.', NOW(), NOW(), NULL),
(7, 'Mapa Táctil del Mundo', 'Mapa en relieve que permite explorar continentes, países y océanos a través del tacto.', NOW(), NOW(), NULL),
(8, 'Audífonos de Alta Fidelidad', 'Audífonos de alta calidad para amplificar sonidos, ideales para estudiantes con baja visión.', NOW(), NOW(), NULL),
(9, 'Software de Reconocimiento de Voz', 'Programa que permite interactuar con el ordenador mediante comandos de voz.', NOW(), NOW(), NULL),
(10, 'Video Descriptivo de Ciencia', 'Material audiovisual con narración descriptiva que explica conceptos científicos para personas ciegas.', NOW(), NOW(), NULL),
(11, 'Etiquetas en Braille para Materiales de Oficina', 'Etiquetas en Braille que pueden colocarse en carpetas, documentos y otros materiales educativos.', NOW(), NOW(), NULL),
(12, 'Smartphone Adaptado', 'Teléfono móvil adaptado con aplicaciones accesibles y configuraciones para usuarios con ceguera.', NOW(), NOW(), NULL),
(13, 'Brazalete Adaptativo para Ejercicios', 'Brazalete táctil para guiar a las personas con ceguera durante ejercicios o actividades físicas.', NOW(), NOW(), NULL),
(14, 'Audífono Bluetooth', 'Audífono inalámbrico compatible con dispositivos Bluetooth, ideal para escuchar audio o instrucciones.', NOW(), NOW(), NULL),
(15, 'Lentes de Lectura para Baja Visión', 'Lentes especialmente diseñados para personas con baja visión, con aumento y contraste mejorado.', NOW(), NOW(), NULL),
(16, 'Escáner de Documentos Portátil', 'Escáner compacto que convierte documentos en texto accesible para personas con ceguera.', NOW(), NOW(), NULL),
(17, 'Pantalla Braille Electrónica', 'Pantalla que convierte texto en caracteres Braille de manera dinámica y en tiempo real.', NOW(), NOW(), NULL),
(18, 'Simulador de Realidad Aumentada', 'Dispositivo que usa realidad aumentada para proporcionar experiencias interactivas adaptadas.', NOW(), NOW(), NULL),
(19, 'Cámara Táctil', 'Cámara adaptada con funciones táctiles para personas con ceguera, permitiendo captar imágenes mediante tacto.', NOW(), NOW(), NULL),
(20, 'Aplicación de Traducción Braille', 'App móvil que convierte texto impreso a Braille, permitiendo traducir documentos accesibles.', NOW(), NOW(), NULL),
(21, 'Herramienta de Orientación Espacial', 'Dispositivo de navegación que usa sonido para guiar al usuario en espacios desconocidos.', NOW(), NOW(), NULL),
(22, 'Sensor de Proximidad Táctil', 'Sensor que emite vibraciones o sonidos para indicar la proximidad de un objeto.', NOW(), NOW(), NULL),
(23, 'Proyector de Mapas Táctiles', 'Proyector que crea mapas táctiles interactivos a gran escala para facilitar el aprendizaje.', NOW(), NOW(), NULL),
(24, 'Teclado Virtual Adaptado', 'Teclado proyectado en una pantalla con opciones táctiles accesibles para personas con ceguera.', NOW(), NOW(), NULL),
(25, 'Lentes de Aumento de Contraste', 'Lentes con alto contraste que mejoran la visibilidad de textos y objetos para personas con baja visión.', NOW(), NOW(), NULL),
(26, 'Cámara de Alta Resolución Adaptada', 'Cámara diseñada para capturar detalles con alta resolución, útil para imágenes táctiles.', NOW(), NOW(), NULL),
(27, 'Sistema de Navegación Sonora', 'Sistema que proporciona información espacial utilizando señales sonoras para guiar a la persona.', NOW(), NOW(), NULL),
(28, 'Simulador de Entrenamiento Braille', 'Simulador interactivo para practicar la lectura y escritura en Braille en tiempo real.', NOW(), NOW(), NULL),
(29, 'Guía Sonora de Ruta', 'Guía portable que usa señales sonoras para orientar a la persona con ceguera en su entorno.', NOW(), NOW(), NULL),
(30, 'Juego Táctil Educativo', 'Juego educativo en relieve y con instrucciones en Braille para niños con ceguera.', NOW(), NOW(), NULL);
